[project]
name = "call_me_maybe"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
	"numpy",
	"pydantic",
	"llm_sdk",
]

[tool.uv.sources]
llm_sdk = { path = "./llm_sdk" }

[tool.mypy]
mypy_path = "llm_sdk"
exclude = ["^llm_sdk/"]

[[tool.mypy.overrides]]
module = ["llm_sdk", "llm_sdk.*"]
follow_imports = "silent"
ignore_missing_imports = true
